name = "NPCs Factions";
author = "Berntsen";
logo = "npc_common\data\ui\npc_logo.paa";
logoOver = "npc_common\data\ui\npc_logo.paa";
picture = "npc_common\data\ui\npc_logo.paa";
actionName = "Github";
action = "https://github.com/TahMahn/npcs_factions";
overview = "NPCs fictional world of warcrimes!";
logosmall = "npc_common\data\ui\npc_logo_small.paa";
